apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke-dev
        image: gcr.io/custom-cable-466509-g1/gcp-devops-dev:$SHORT_SHA
        ports:
        - containerPort: 5050
        env:
         - name: PORT
           value: "5050"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-devops-gke-dev-service"
  namespace: "gcp-devops-dev"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5050
  selector:
    app: gcp
  type: "LoadBalancer"